server:
  port: 8080   # Render will override with $PORT automatically

spring:
  datasource:
    url: jdbc:postgresql://dpg-d6g5v4lm5p6s73970570-a:5432/hospital_scheduler_postgres
    username: hospital_scheduler_postgres_user
    password: LKVjyZSt1nBFoxW4WPwFerE6eIq4TwKW
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # automatically create/update tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
